### ISSUE TITLE
Main menu improvement: Add one-time hint screen

### ISSUE THREAD

**Issue by s0rent** [JackD83/PyMenu#1]
I suggest removing the bottom section of the screen ("select", "options", "open" hints), and replace it with a one-time hint screen that is only displayed the first time you open the UI. 

The navigation hints are somewhat intuitive already, so showing the information only once should be enough. It will make the main menu clutter free and look better. 

Sketch:
![menuredesign](https://user-images.githubusercontent.com/11552352/37678977-e98dade0-2c7f-11e8-82fa-5aa40f1f5fe3.gif)

**Comment by JackD83** [comment]
Removing the footer is no problem. Do you mean remove it only on the first screen or on all screens? 
Some screens like file selection and text input have a slightly different button layout
