### ISSUE TITLE
Main menu improvement: Remove top bar

### ISSUE THREAD

**Issue by s0rent** [JackD83/PyMenu#2]
I suggest removing the top bar background, and the "SD"? card icon. 

![menuredesign2](https://user-images.githubusercontent.com/11552352/37679284-c11be5ba-2c80-11e8-8ce1-0ddccdd2dd6c.jpg)
(1) Is this a volume indicator? Should be made optional via config for devices with HW potentiometer
(2) Battery indicator should stay of course
I suggest placing them in each their corner in the upper portion of the screen. 

I can help draw new graphics for the volume and battery.

**Comment by JackD83** [comment]
(1) should be the volume...
We have to consider that the background image can be any color. The icons have to be visible on any background

New icons are always appreciated! X, Y, L, R are also missing
