### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by blackz1982** [JackD83/PyMenu#3]
it is right?
1) "icon": "C:\\Projekte\\Projekte\\Privat\\py\\PyMenu\\systems\\snes.png", "selectionPath": "C:\\snes\\Roms", "workingDir": "C:/tmp/snes9x/", "cmd": "C:/tmp/snes9x/snes9x.exe", "previews": "C:\\snes\\Artwork\\Box Front"
2) "name": "DinguxExplorer", "cmd": "C:\\Projekte\\Projekte\\Privat\\py\\PyMenu\\InfoOverlay.py", "icon": "", "preview": "C:\\Projekte\\Projekte\\Privat\\py\\PyMenu\\backgrounds\\a2600_art_blur.jpg"

**Comment by JackD83** [comment]
On my machine, yes. On yours probably not :P
That's the result of using the edit option in the menu. It uses absolute paths. Just delete those two or edit it using menu itselfe
