### ISSUE TITLE
No sound on most recent release

### ISSUE THREAD

**Issue by TheTrainGoes** [JackD83/PyMenu#6]
I have lost all sound on the most recent release.  

Is there something I need to do to restore sound?  I am able to replace the PyMenu with an older version to restore sound.

**Comment by JackD83** [comment]
Are you using the UselessRS97 firmware? PyMenu is using a native component "setVolume" that changed in the latest versions and depends on the Useless fw. The older fw Rs97Next is no longer supported. 

You can use the setVolume from an older PyMenu to get it working, but other things like USB mounting might not work
