### ISSUE TITLE
Possible to set default view / preview?

### ISSUE THREAD

**Issue by TheTrainGoes** [JackD83/PyMenu#7]
Is it possible to set the default view and preview options on the game selection screen?

I have looked in the ConfigMenu.py file but cannot get anything to change by default.

**Comment by JackD83** [comment]
What do you mean by "default view and preview options"? The default paths for the previews?

**Comment by TheTrainGoes** [comment]
Hello,

After selecting a system, you are brought to the file browser / selector. 

By default, I am brought to a screen that shows the directory contents on the right, and, presumably, the preview section on the left.  Pressing X changes the view to where the preview is in the top right, and then pressing Y removes the preview altogether.  

I would like to have that be the default view.  How can I change this?  I was not able to find it in the .py files.

Thanks!

I have attached two pics for you.

![img_3013](https://user-images.githubusercontent.com/32771064/46634284-57f60b00-cb1e-11e8-9e4a-0302a8d199e8.JPG)
![img_3388](https://user-images.githubusercontent.com/32771064/46634285-57f60b00-cb1e-11e8-8ffa-1a49be2cb718.JPG)

**Comment by JackD83** [comment]
Thats easy. I called the things on the left "sidebar". How the list is rendered is controlled by some options that are defined on opening. 

The parameter you seek is in MainMenu.py line 195

` options["useSidebar"] = False`

Set this to False and the list for emulators will start only with the header

**Comment by TheTrainGoesChoo** [comment]
Thank you!  That part worked like a charm!

Is there any way to default without the `preview` section?  

This is the part where pressing the `X` button toggles is.

Amazing work by the way!  And thank you so much for the replies :)

![img_7127](https://user-images.githubusercontent.com/32882807/46671952-2cb5ff00-cba4-11e8-934f-3f130f593172.JPG)
![img_2895](https://user-images.githubusercontent.com/32882807/46671956-30498600-cba4-11e8-801a-9137f99cfcf6.JPG)

**Comment by JackD83** [comment]
Do you have the latest git version? X toggles now between the preview image and a possible description. The box should be longe gone

**Comment by TheTrainGoesChoo** [comment]
Newest version causes no sound (my other open issue), and I have yet to troubleshoot that.

I am going to try re-downloading the base image and adding PyMenu again then see what happens.  Will be easier to troubleshoot if I am using the most recent version.

Thank you for your help so far!
